#!/bin/bash

TCR_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TCR_HOME="${TCR_HOME:-"$(cd "$(dirname "$0")" && pwd)"}"

TCR_WORK_DIRECTORY="${TCR_WORK_DIRECTORY:-"$(pwd)"}"

source "$TCR_HOME/lib/foundation.sh"
source "$TCR_HOME/lib/tcr/actions.sh"
source "$TCR_HOME/lib/tcr/options.sh"

tcr() {
    local arguments="$*"
    local action="$1"

    if is_containing "$arguments" "$TCR_OPTION_HELP"; then
        tcr_option_help
        return
    fi

    if is_unset "$action"; then
        error_raise "$TCR_ERROR_TCR_ARGUMENTS_MISSING"
        return
    fi

    case "$action" in
        "$TCR_ACTION_ENABLE")
            tcr_action_enable
            ;;
        "$TCR_ACTION_DISABLE")
            tcr_action_disable
            ;;
        "$TCR_ACTION_RUN")
            if ! tcr_is_enabled; then
                error_raise "$TCR_ERROR_TCR_NOT_ENABLED"
                return
            fi

            tcr_action_run
            ;;
        "$TCR_ACTION_INIT")
            tcr_action_init
            ;;
        "$TCR_ACTION_STATUS")
            tcr_action_status
            ;;
        *)
            error_raise "$TCR_ERROR_TCR_UNKNOWN_ACTION"
        ;;
    esac
}

tcr_is_enabled() {
    lock_file_is_existing
}

# -- Main -- #

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    tcr "$@"
fi