#!/bin/bash

set -e

file_absolute_dir_path() {
    local file_path="$1"
    local file_dir
    local absolute_file_dir_path

    if [ -L "$file_path" ]; then
        file_path="$(readlink "$0")"
    fi

    file_dir="$(dirname "$file_path")"
    absolute_file_dir_path="$(cd "$file_dir" && pwd)"

    echo "$absolute_file_dir_path"
}

TCR_HOME="$(file_absolute_dir_path "${BASH_SOURCE[0]}")"
TCR_HOME="${TCR_HOME:-"$(file_absolute_dir_path "$0")"}"

TCR_WORK_DIRECTORY="${TCR_WORK_DIRECTORY:-"$(pwd)"}"

source "$TCR_HOME/lib/foundation.sh"
source "$TCR_HOME/lib/tcr/tcr_foundation.sh"
source "$TCR_HOME/lib/tcr/actions.sh"
source "$TCR_HOME/lib/tcr/options.sh"

tcr() {
    local arguments="$*"
    local action="$1"

    if is_containing "$arguments" "$TCR_OPTION_HELP"; then
        tcr_option_help
        return "$(last_command_status)"
    elif is_containing "$arguments" "$TCR_OPTION_VERSION"; then
        tcr_option_version
        return "$(last_command_status)"
    fi

    if is_unset "$action"; then
        error_raise "$TCR_ERROR_TCR_ARGUMENTS_MISSING"
        return "$(latest_error_code)"
    fi

    case "$action" in
        "$TCR_ACTION_ENABLE")
            tcr_action_enable "$@"
            ;;
        "$TCR_ACTION_DISABLE")
            tcr_action_disable
            ;;
        "$TCR_ACTION_RUN")
            if ! tcr_is_enabled; then
                error_raise "$TCR_ERROR_TCR_NOT_ENABLED"
                return "$(latest_error_code)"
            fi

            tcr_action_run
            ;;
        "$TCR_ACTION_INIT")
            tcr_action_init
            ;;
        "$TCR_ACTION_STATUS")
            tcr_action_status
            ;;
        "$TCR_ACTION_WATCH")
            tcr_action_watch
            ;;
        *)
            error_raise "$TCR_ERROR_TCR_UNKNOWN_ACTION"
            return "$(latest_error_code)"
        ;;
    esac
}

# -- Main -- #

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    tcr "$@"
fi