#!/bin/bash

TEST_BUILD_CMD='echo "Building project"'
TEST_TEST_CMD='echo "Running tests"'
TEST_COMMIT_CMD='echo "Committing changes"'
TEST_REVERT_CMD='echo "Reverting changes"'
TEST_CHANGE_DETECTION_CMD='echo "Watching for changes'
TEST_NOTIFICATION_SUCCESS_CMD="echo 'TCR run successful!'"
TEST_NOTIFICATION_FAILURE_CMD="echo 'TCR run failed!'"
TEST_ACTION_RUN_CFG_PATH='./spec/fixtures/config_fixture.tcrcfg'
tcr_load_config() {
    TCR_BUILD_CMD="$TEST_BUILD_CMD"
    TCR_TEST_CMD="$TEST_TEST_CMD"
    TCR_COMMIT_CMD="$TEST_COMMIT_CMD"
    TCR_REVERT_CMD="$TEST_REVERT_CMD"
    TCR_CHANGE_DETECTION_CMD="$TEST_CHANGE_DETECTION_CMD"
    TCR_NOTIFICATION_SUCCESS_CMD="$TEST_NOTIFICATION_SUCCESS_CMD"
    TCR_NOTIFICATION_FAILURE_CMD="$TEST_NOTIFICATION_FAILURE_CMD"
    
    TCR_ACTION_RUN_CFG_PATH="$TEST_ACTION_RUN_CFG_PATH"
}